sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t mbychkov/docker-react -f Dockerfile.dev .

script:
  - docker run USERNAME/docker-react npm run test -- --coverage